name: Build Custom Telegram APK

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clone Telegram Client Source
        run: |
          git clone --depth 1 https://github.com/Telegram-FOSS-Team/Telegram-FOSS.git tg-client

      - name: Build APK with Gradle
        run: |
          cd tg-client
          # Пропускаем подпись и собираем базовый отладочный APK
          ./gradlew assembleAfatDebug --no-daemon || ./gradlew assembleDebug --no-daemon

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Shinygram
          path: tg-client/TMessagesProj/build/outputs/apk/**/*.apk
          
